CREATE TABLE s367595.blps_ad_campaign
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url          VARCHAR(255),
    ad_goal_name VARCHAR(255)                            NOT NULL,
    ad_type_name VARCHAR(255)                            NOT NULL,
    "limit"      INTEGER,
    start_date   TIMESTAMP WITHOUT TIME ZONE,
    end_date     TIMESTAMP WITHOUT TIME ZONE,
    owner_id     BIGINT,
    CONSTRAINT pk_blps_ad_campaign PRIMARY KEY (id)
);

CREATE TABLE s367595.blps_ad_goal
(
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_blps_ad_goal PRIMARY KEY (name)
);

CREATE TABLE s367595.blps_ad_group
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    regions                        JSONB,
    is_allow_expansion_of_audience BOOLEAN                                 NOT NULL,
    min_age                        INTEGER,
    max_age                        INTEGER,
    interests                      JSONB,
    is_allow_desktop               BOOLEAN                                 NOT NULL,
    is_allow_mobile                BOOLEAN                                 NOT NULL,
    ad_campaign_id                 BIGINT                                  NOT NULL,
    CONSTRAINT pk_blps_ad_group PRIMARY KEY (id)
);

CREATE TABLE s367595.blps_ad_type
(
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    img_url     VARCHAR(255),
    CONSTRAINT pk_blps_ad_type PRIMARY KEY (name)
);

CREATE TABLE s367595.blps_advertising_cabinet
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type                    VARCHAR(255),
    country                 VARCHAR(255),
    currency                VARCHAR(255),
    email                   VARCHAR(255),
    owner_type              VARCHAR(255),
    inn                     VARCHAR(255),
    full_name               VARCHAR(255),
    is_agree_to_receive_ads BOOLEAN                                 NOT NULL,
    owner_id                BIGINT,
    CONSTRAINT pk_blps_advertising_cabinet PRIMARY KEY (id)
);

CREATE TABLE s367595.blps_announcement
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id          BIGINT,
    title             VARCHAR(255),
    short_description VARCHAR(255),
    long_description  VARCHAR(255),
    text_near_button  VARCHAR(255),
    url               VARCHAR(255),
    text_on_button    VARCHAR(255),
    img_url           VARCHAR(255),
    advertiser_info   VARCHAR(255),
    status            VARCHAR(255),
    CONSTRAINT pk_blps_announcement PRIMARY KEY (id)
);

ALTER TABLE s367595.blps_ad_campaign
    ADD CONSTRAINT FK_BLPS_AD_CAMPAIGN_ON_AD_GOAL_NAME FOREIGN KEY (ad_goal_name) REFERENCES s367595.blps_ad_goal (name);

ALTER TABLE s367595.blps_ad_campaign
    ADD CONSTRAINT FK_BLPS_AD_CAMPAIGN_ON_AD_TYPE_NAME FOREIGN KEY (ad_type_name) REFERENCES s367595.blps_ad_type (name);

ALTER TABLE s367595.blps_ad_group
    ADD CONSTRAINT FK_BLPS_AD_GROUP_ON_AD_CAMPAIGN FOREIGN KEY (ad_campaign_id) REFERENCES s367595.blps_ad_campaign (id);

ALTER TABLE s367595.blps_announcement
    ADD CONSTRAINT FK_BLPS_ANNOUNCEMENT_ON_GROUP FOREIGN KEY (group_id) REFERENCES s367595.blps_ad_group (id);