

CREATE TABLE s367595.blps_community
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                      VARCHAR(255),
    is_allowed_to_make_donuts BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_blps_community PRIMARY KEY (id)
);

CREATE TABLE s367595.blps_donut_goal
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goal         INTEGER,
    title        VARCHAR(255),
    description  VARCHAR(255),
    community_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_blps_donut_goal PRIMARY KEY (id)
);

CREATE TABLE s367595.blps_donut_level
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount       INTEGER,
    title        INTEGER,
    description  INTEGER,
    community_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_blps_donut_level PRIMARY KEY (id)
);

CREATE TABLE s367595.blps_payment_card
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token   VARCHAR(255),
    type    VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT pk_blps_payment_card PRIMARY KEY (id)
);

ALTER TABLE s367595.blps_donut_goal
    ADD CONSTRAINT FK_BLPS_DONUT_GOAL_ON_COMMUNITY FOREIGN KEY (community_id) REFERENCES s367595.blps_community (id);

ALTER TABLE s367595.blps_donut_level
    ADD CONSTRAINT FK_BLPS_DONUT_LEVEL_ON_COMMUNITY FOREIGN KEY (community_id) REFERENCES s367595.blps_community (id);