CREATE TABLE s367595.blps_phone_auth_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(11)                             NOT NULL,
    code         VARCHAR(4),
    datetime     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    register     BOOLEAN,
    attempts     INTEGER,
    provider     VARCHAR(255),
    CONSTRAINT pk_blps_phone_auth_requests PRIMARY KEY (id)
);

CREATE TABLE s367595.blps_refresh_storage
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    refresh_token VARCHAR(255),
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_blps_refresh_storage PRIMARY KEY (id)
);

CREATE TABLE s367595.blps_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    phone    VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_blps_user PRIMARY KEY (id)
);

ALTER TABLE s367595.blps_ad_group
    DROP COLUMN interests;

ALTER TABLE s367595.blps_ad_group
    ADD interests VARCHAR(255);